# Generated by Django 2.1.8 on 2019-07-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halfthonapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='attend',
            field=models.BooleanField(default=False),
        ),
    ]
